/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "dashboard": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "espacos.index": [],
    "espacos.create": [],
    "espacos.store": [],
    "espacos.show": [
        {
            "name": "espaco",
            "required": true
        }
    ],
    "espacos.edit": [
        {
            "name": "espaco",
            "required": true
        }
    ],
    "espacos.update": [
        {
            "name": "espaco",
            "required": true
        }
    ],
    "espacos.destroy": [
        {
            "name": "espaco",
            "required": true
        }
    ],
    "localizacoes.index": [],
    "localizacoes.create": [],
    "localizacoes.show": [
        {
            "name": "localizacao",
            "required": true
        }
    ],
    "localizacoes.store": [],
    "localizacoes.edit": [
        {
            "name": "localizacao",
            "required": true
        }
    ],
    "localizacoes.update": [
        {
            "name": "localizacao",
            "required": true
        }
    ],
    "localizacoes.destroy": [
        {
            "name": "localizacao",
            "required": true
        }
    ],
    "recursos.index": [],
    "recursos.create": [],
    "recursos.store": [],
    "recursos.show": [
        {
            "name": "recurso",
            "required": true
        }
    ],
    "recursos.edit": [
        {
            "name": "recurso",
            "required": true
        }
    ],
    "recursos.update": [
        {
            "name": "recurso",
            "required": true
        }
    ],
    "recursos.destroy": [
        {
            "name": "recurso",
            "required": true
        }
    ],
    "espaco-users.index": [],
    "espaco-users.create": [],
    "espaco-users.store": [],
    "espaco-users.show": [
        {
            "name": "espacoUser",
            "required": true
        }
    ],
    "espaco-users.atribuir": [
        {
            "name": "id",
            "required": true
        }
    ],
    "espaco-users.update": [
        {
            "name": "espacoUser",
            "required": true
        }
    ],
    "espaco-users.destroy": [
        {
            "name": "espacoUser",
            "required": true
        }
    ],
    "fotos.index": [],
    "fotos.create": [],
    "fotos.store": [],
    "fotos.show": [
        {
            "name": "foto",
            "required": true,
            "binding": "id"
        }
    ],
    "fotos.edit": [
        {
            "name": "foto",
            "required": true
        }
    ],
    "fotos.update": [
        {
            "name": "foto",
            "required": true,
            "binding": "id"
        }
    ],
    "fotos.destroy": [
        {
            "name": "foto",
            "required": true,
            "binding": "id"
        }
    ],
    "fotos.reorder": [],
    "agendamentos.index": [],
    "agendamentos.create": [],
    "agendamentos.store": [],
    "agendamentos.verificar-disponibilidade": [],
    "agendamentos.show": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "agendamentos.edit": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "agendamentos.update": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "agendamentos.destroy": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "agendamentos.gerenciar": [],
    "agendamentos.aprovar": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "agendamentos.rejeitar": [
        {
            "name": "agendamento",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
